import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import PageLayout from "./PageContainer";
import { useGetReport } from "@/hooks/useGetReport";
import { Button } from "@/components/ui/button";
import { DownloadIcon } from "lucide-react";
import CustomAccordion from "@/components/custom/CustomAccordion";
import { IconEyeDotted } from "@tabler/icons-react";

const ReportDetails = () => {
    const { reportId } = useParams();
    const { getReport } = useGetReport();
    const [report, setReport] = useState<any>(null);
    const [status, setStatus] = useState<"idle" | "loading" | "error" | "success">("idle");
    const [error, setError] = useState<string | null>(null);


    useEffect(() => {
        if (!reportId) return

        setStatus("loading")
        getReport(reportId)
            .then((rep: any) => {
            setReport(rep)
            // console.log(rep)
            setStatus("success")
            })
            .catch((err) => {
            setError(err.message || "Unknown error")
            console.log(err)
            setStatus("error")
            })
    }, [reportId, getReport]);

    if (status === "loading") {
        return <PageLayout><div>Loading report...</div></PageLayout>;
    }
    if (status === "error") {
        return <PageLayout><div>Error: {error}</div></PageLayout>;
    }

    return (
        <PageLayout>
            <div className="flex flex-col gap-4 text-sm">
            
                {/* <!-- Report Header --> */}
                <div className="flex justify-between items-center text-sm">
                    <p>Generated by: <span className="rounded-md border border-green/50 bg-green/50 py-1 px-2">{report?.generated_by} </span></p>
                    {/* <p>Date Generated: {report?.generated_at} </p> */}
                    <div className="flex gap-2">
                        <Button variant="outline" className="flex items-center gap-2 cursor-pointer">
                            <IconEyeDotted className="w-4 h-4" />
                            Add Review
                        </Button>
                        <Button variant="outline" className="flex items-center gap-2 cursor-pointer">
                            <DownloadIcon className="w-4 h-4" />
                            Download
                        </Button>

                    </div>
                </div>

                <section className="flex flex-col gap-4 lg:w-3/5 mx-auto my-12">
                    
                    {/* <!-- 1. Patient Demographics --> */}
                    <CustomAccordion title="Patient Demographics">
                        <ul>
                            <li><strong>Patient ID:</strong> {report?.patient_demographics?.patient_id}</li>
                            <li><strong>Age:</strong> {report?.patient_demographics?.age}</li>
                            <li><strong>Gender:</strong> {report?.patient_demographics?.gender}</li>
                            <li><strong>Height:</strong> {report?.patient_demographics?.height} cm</li>
                            <li><strong>Weight:</strong> {report?.patient_demographics?.weight} kg</li>
                            <li><strong>Ethnicity:</strong> {report?.patient_demographics?.ethnicity}</li>
                            <li><strong>Smoking Status:</strong> {report?.patient_demographics?.smoking_status}</li>
                        </ul>
                    </CustomAccordion>
                    

                    {/* <!-- 2. Test Information --> */}
                    <CustomAccordion title="Test Information" open={false}>
                    <ul>
                        <li><strong>Date:</strong> {report?.test_date}</li>
                        <li><strong>Workflow Version:</strong> {report?.workflow_version}</li>
                        <li><strong>Agents Used:</strong> {report?.agents_used?.join(", ")}</li>
                    </ul>
                    </CustomAccordion>

                    {/* <!-- 3. Raw Data & Predictions --> */}
                    <CustomAccordion title="Raw Data & Predicted Values">
                    <table>
                        <thead><tr><th>Parameter</th><th>Measured</th><th>Predicted</th><th>% Predicted</th></tr></thead>
                        <tbody>
                        <tr><td>FVC</td><td>{report?.raw_data?.fvc}</td><td>(empty)</td><td>(empty)</td></tr>
                        <tr><td>FEV₁</td><td>{report?.raw_data?.fev1}</td><td>(empty)</td><td>(empty)</td></tr>
                        <tr><td>PEF</td><td>{report?.raw_data?.pef}</td><td>(empty)</td><td>(empty)</td></tr>
                        <tr><td>FEF₂₅–₇₅</td><td>{report?.raw_data?.fef2575}</td><td>(empty)</td><td>(empty)</td></tr>
                        </tbody>
                    </table>
                    </CustomAccordion>

                    {/* <!-- 4. Quality Metrics --> */}
                    <CustomAccordion title="Quality Metrics">
                    <summary><strong>Quality Metrics</strong></summary>
                    <ul>
                        <li><strong>Data Completeness:</strong> {report?.quality_metrics?.data_completeness}%</li>
                        <li><strong>Measurement Quality:</strong> {report?.quality_metrics?.measurement_quality}</li>
                        <li><strong>Missing Parameters:</strong> {report?.quality_metrics?.missing_parameters?.join(", ")}</li>
                        <li><strong>Data Quality Issues:</strong> {report?.quality_metrics?.data_quality_issues?.join(", ")}</li>
                    </ul>
                    </CustomAccordion>

                    {/* <!-- 5. Interpretation --> */}
                    <CustomAccordion title="Interpretation">
                    <summary><strong>Interpretation</strong></summary>
                    <ul>
                        <li><strong>Pattern:</strong> {report?.interpretation?.pattern}</li>
                        <li><strong>Severity:</strong> {report?.interpretation?.severity}</li>
                        <li><strong>Obstruction:</strong> {report?.interpretation?.obstruction ? "yes" : "no"}  <strong>Restriction:</strong> {report?.interpretation?.restriction ? "yes" : "no"}</li>
                        <li><strong>Reversibility:</strong> {report?.interpretation?.reversibility}</li>
                        <li><strong>Key Findings:</strong> {report?.interpretation?.key_findings?.join(", ")}</li>
                        <li><strong>Trend Analysis:</strong> {report?.interpretation?.trend_analysis}</li>
                        <li><strong>Clinical Significance:</strong> {report?.interpretation?.clinical_significance}</li>
                        <li><strong>Follow‑up Recommendations:</strong> {report?.interpretation?.follow_up_recommendations}</li>
                        <li><strong>Interpretation Rationale:</strong> {report?.interpretation?.rationale}</li>
                    </ul>
                    </CustomAccordion>

                    {/* <!-- 6. Triage Assessment --> */}
                    <CustomAccordion title="Triage Assessment">
                    <summary><strong>Triage Assessment</strong></summary>
                    <ul>
                        <li><strong>Level:</strong> {report?.triage_assessment?.level}</li>
                        <li><strong>Reasons:</strong> {report?.triage_assessment?.reasons?.join(", ")}</li>
                        <li><strong>Recommended Follow‑up:</strong> {report?.triage_assessment?.follow_up_recommended}</li>
                        <li><strong>Immediate Actions:</strong> {report?.triage_assessment?.immediate_actions?.join(", ")}</li>
                        <li><strong>Monitoring Requirements:</strong> {report?.triage_assessment?.monitoring_requirements?.join(", ")}</li>
                        <li><strong>Follow‑up Instructions:</strong>
                        <ul>
                            <li>{report?.triage_assessment?.follow_up_instructions?.map((item: string, index: number) => (
                                <span key={index}>{item}{index < report?.triage_assessment?.follow_up_instructions?.length - 1 ? ", " : ""}</span>
                            ))}</li>
                        </ul>
                        </li>
                    </ul>
                    </CustomAccordion>

                    {/* <!-- 7. Report Content --> */}
                    <CustomAccordion title="Report Content">
                    <summary><strong>Report Content</strong></summary>
                    <h4>Clinical Summary</h4>
                    <p>A {report?.patient_demographics?.age}‑year‑old {report?.patient_demographics?.gender} underwent pulmonary function testing on {report?.test_date}…</p>

                    <h4>Detailed Interpretation</h4>
                    <p>The pulmonary function test (PFT) results demonstrate a {report?.interpretation?.pattern} spirometric pattern…</p>

                    <h4>Recommendations</h4>
                    <p>Maintain routine yearly PFT follow‑ups…</p>

                    <h4>Technical Summary</h4>
                    <p>Performing the PFT on the provided date yielded results consistent with a normal respiratory profile…</p>

                    <h4>Patient Summary</h4>
                    <p>Your recent lung function test shows that your lung capacity and airflow are within the normal range…</p>

                    <h4>Section Breakdowns</h4>
                    <ul>
                        <li><strong>Demographics:</strong> Patient ID: {report?.patient_demographics?.patient_id}, Age: {report?.patient_demographics?.age}…</li>
                        <li><strong>Test Info:</strong> PFT conducted on {report?.test_date}</li>
                        <li><strong>Results Table:</strong> FVC: {report?.raw_data?.fvc}, FEV₁: {report?.raw_data?.fev1}…</li>
                        <li><strong>Clinical Significance:</strong> No concerns; monitor regularly</li>
                        <li><strong>Technical Notes:</strong> Automated rule‑based interpretation…</li>
                        <li><strong>Historical Comparison:</strong> No previous data available</li>
                    </ul>

                    <h4>Key Findings</h4>
                    <ul>
                        <li>Normal spirometric results indicating no obstruction or restriction.</li>
                        <li>Low FEF₂₅–₇₅ but not clinically significant at this time.</li>
                    </ul>

                    <h4>Follow‑up Timeline</h4>
                    <p>Routine follow‑up in {report?.triage_assessment?.follow_up_recommended?.split(" ")[0]}–{report?.triage_assessment?.follow_up_recommended?.split(" ")[2]}; annual PFT thereafter.</p>

                    <h4>Scores</h4>
                    <ul>
                        <li>Report Quality Score: {report?.quality_assessment?.report_quality_score}</li>
                        <li>Completeness Score: {report?.quality_assessment?.completeness_score}</li>
                    </ul>
                    </CustomAccordion>

                    {/* <!-- 8. Quality Assessment --> */}
                    <CustomAccordion title="Quality Assessment">
                    <summary><strong>Quality Assessment</strong></summary>
                    <ul>
                        <li><strong>Overall Quality:</strong> {report?.quality_assessment?.overall_quality}</li>
                        <li><strong>Completeness:</strong> {report?.quality_assessment?.completeness}</li>
                        <li><strong>Clarity:</strong> {report?.quality_assessment?.clarity}</li>
                        <li><strong>Medical Accuracy:</strong> {report?.quality_assessment?.medical_accuracy}</li>
                        <li><strong>Formatting:</strong> {report?.quality_assessment?.formatting}</li>
                        <li><strong>Recommendations Quality:</strong> {report?.quality_assessment?.recommendations_quality}</li>
                        <li><strong>Strengths:</strong>
                        <ul>
                            <li>Comprehensive demographics and test info.</li>
                            <li>Clear summary and patient‑friendly explanation.</li>
                        </ul>
                        </li>
                        <li><strong>Areas for Improvement:</strong>
                        <ul>
                            <li>Specify normal reference ranges for context.</li>
                            <li>Clarify follow‑up timeline consistency.</li>
                            <li>Explain low FEF₂₅–₇₅ relevance explicitly.</li>
                        </ul>
                        </li>
                        <li><strong>Critical Issues:</strong> {report?.quality_assessment?.critical_issues}</li>
                        <li><strong>Approval Status:</strong> {report?.quality_assessment?.approval_status}</li>
                    </ul>
                    </CustomAccordion>

                    {/* <!-- 9. Processing Metadata --> */}
                    <CustomAccordion title="Processing Metadata">
                    <ul>
                        <li><strong>Generated By:</strong> {report?.processing_metadata?.generated_by}</li>
                        <li><strong>Generated At:</strong> {report?.processing_metadata?.generated_at}</li>
                        <li><strong>Workflow Version:</strong> {report?.processing_metadata?.workflow_version}</li>
                        <li><strong>Processing Time:</strong> {report?.processing_metadata?.processing_time} s</li>
                        <li><strong>Agents Used:</strong> {report?.processing_metadata?.agents_used?.join(", ")}</li>
                    </ul>
                    </CustomAccordion>
                    
                </section>

            </div>
        </PageLayout>
    )
}

export default ReportDetails;